### ISSUE TITLE
missing footnotes from SecureFirmwareDevelopmentBestPractices.md

### ISSUE THREAD

**Issue by syncsrc** [opencomputeproject/Security#4]
footnotes 1-4 appear to have been lost during the markdown conversion.

**Comment by orangecms** [comment]
I just went through:

- footnotes 1, 3 and 4 are retained as links which are still in the document
- footnote 2 is the call to fork this repostory, so from the Google doc, it made sense to have a link here; now it's just rewritten to refer to the repo itself, so that's just fine :)

https://github.com/opencomputeproject/Security/commit/e6dfd1e7f48dbd0b5bcda10cb6469303fb3ebfab worked on footnote 2, just for reference.

Or did you mean something else? Otherwise, I think the issue can be closed.

**Comment by syncsrc** [comment]
Agreed, looks like that commit fixed the footnotes.
